version: '3'
services:
  web:
    build: .
    ports:
     - 4000:4000
    command: node ./index.js
    volumes:
     - .:/code
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

  